services:

  db-push:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - push_network

  web:
    tty: true
    stdin_open: true
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - push_network


volumes:
  pgdata:

networks:
  push_network:
    external: true
