services:
  web:
    tty: true
    stdin_open: true
    build: .

    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    #command: gunicorn -c gunicorn.conf.py -w 1 app:app
    command: python app.py
    networks:
      - push_network



networks:
  push_network:
    driver: bridge
