services:
  web:
    tty: true
    stdin_open: true
    build: .
    restart: always
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    command: gunicorn -c gunicorn.conf.py run:app
    networks:
      - push_network



networks:
  push_network:
    external: true
